# Windows Whisper Speech-to-Text Configuration
# 
# This file contains all the settings you can customize for the application.
# Edit the values below and restart the app to apply changes.

# =============================================================================
# WHISPER AI MODEL SETTINGS
# =============================================================================
whisper:
  # Model size - affects accuracy vs speed tradeoff
  # Options: "tiny", "base", "small", "medium", "large", "tiny.en", "base.en", "small.en", "medium.en"
  # Multilingual models:
  # - tiny: ~39MB, fastest, good for most use cases
  # - base: ~74MB, better accuracy, still fast
  # - small: ~244MB, high accuracy, slower
  # - medium: ~769MB, very high accuracy, much slower
  # - large: ~1550MB, best accuracy, very slow (not recommended for real-time)
  # English-only models (more accurate, slightly faster):
  # - tiny.en: 39MB, 
  # - base.en: 74MB, 
  # - small.en: 244MB, 
  # - medium.en: 769MB
  model_size: tiny
  
  # Processing device - where the AI runs
  # Options: "cpu", "cuda" (for NVIDIA GPUs)
  # Note: "cuda" requires compatible GPU and drivers
  device: cpu
  
  # Compute precision - affects speed vs accuracy
  # Options: "int8", "float16", "float32"
  # - int8: fastest, good quality (recommended)
  # - float16: balanced (requires GPU for best performance)
  # - float32: highest quality, slowest
  compute_type: int8
  
  # Language detection
  # Options: auto (auto-detect), en, es, fr, de, etc.
  # Set to specific language code to force language, or auto for auto-detection
  language: auto
  
  # Transcription quality settings
  beam_size: 5  # Higher = more accurate but slower (1-10)

# =============================================================================
# HOTKEY CONFIGURATION
# =============================================================================
hotkey:
  # Key combination to start/stop recording
  # Format: modifier+modifier+key (use lowercase)
  # Common modifiers: ctrl, shift, alt, win
  # Examples:
  #   - "ctrl+shift+space"     (default)
  #   - "ctrl+alt+r"
  #   - "win+shift+v"
  #   - "ctrl+shift+f12"
  combination: ctrl+win
  
  # Auto-ENTER hotkey - Stop recording and send automatic ENTER key press after
  # (This hotkey cannot start recording)
  auto_enter_combination: alt+win
  
  # Enable/disable the auto-ENTER hotkey functionality
  auto_enter_enabled: true
  
  # Delay for key simulation operations (seconds)
  # Small delay ensures operations complete reliably
  key_simulation_delay: 0.05
  
  # Stop recording with just the first modifier key
  # If enabled, you can stop recording by pressing just the first modifier 
  # (e.g., if your combination is 'ctrl+win', just pressing 'ctrl' will stop)
  # (e.g., if your combination is 'ctrl+shift+t', just pressing 'ctrl' will stop)
  # This provides a simpler way to stop recording without the full key combination
  stop_with_modifier_enabled: true

# =============================================================================
# AUDIO RECORDING SETTINGS
# =============================================================================
audio:
  # Sample rate for recording (Hz)
  # Higher = better quality but larger files
  # Common values: 16000, 22050, 44100, 48000
  # Note: Whisper works best with 16000 Hz
  sample_rate: 16000
  
  # Audio channels
  # 1 = mono (recommended for speech)
  # 2 = stereo
  channels: 1
  
  # Recording format
  # Options: "float32", "int16", "int24", "int32"
  # float32 recommended for best quality
  dtype: float32
  
  # Maximum recording duration (seconds)
  # Set to 0 for unlimited recording
  max_duration: 30

# =============================================================================
# CLIPBOARD BEHAVIOR
# =============================================================================
clipboard:
  # Automatically paste after transcription
  # true = paste immediately to active window
  # false = only copy to clipboard (paste manually with Ctrl+V)
  auto_paste: true
  
  # Method for auto-pasting (when auto_paste is true)
  # Options: "key_simulation", "windows_api"
  # - key_simulation: Simulates Ctrl+V keypress (recommended - works with most apps)
  # - windows_api: Direct Windows API paste (faster but less compatible)
  paste_method: key_simulation
  
  # Add extra formatting to transcribed text
  # Options: "none", "capitalize", "sentence"
  # - none: exact transcription
  # - capitalize: Capitalize first letter
  # - sentence: Capitalize first letter and add period if missing
  text_formatting: none
  
  # Preserve existing clipboard content when pasting
  # true = save current clipboard, paste transcription, then restore original clipboard
  # false = replace clipboard with transcription (default behavior)
  preserve_clipboard: true

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  # Log level - how much detail to log
  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  # - DEBUG: Very detailed (for troubleshooting)
  # - INFO: General information (recommended)
  # - WARNING: Only warnings and errors
  # - ERROR: Only errors
  level: INFO
  
  # Log file settings
  file:
    enabled: true
    filename: app.log
    max_size_mb: 10  # Rotate log when it gets this big
    backup_count: 3  # Keep this many old log files
  
  # Console output
  console:
    enabled: true
    level: WARNING  # Console log level (DEBUG, INFO, WARNING, ERROR, CRITICAL) - WARNING shows important messages only
    colored: true  # Use colored output in terminal (if supported)

# =============================================================================
# PERFORMANCE SETTINGS
# =============================================================================
performance:
  # CPU threads to use for processing
  # 0 = auto-detect (recommended)
  # Higher numbers may speed up transcription on multi-core systems
  cpu_threads: 0
  
  # Memory management
  # true = clear model cache between transcriptions (saves memory)
  # false = keep model in memory (faster but uses more RAM)
  clear_cache: false

# =============================================================================
# AUDIO FEEDBACK SETTINGS
# =============================================================================
audio_feedback:
  # Enable/disable audio feedback sounds
  # true = play sounds when recording starts/stops
  # false = silent operation
  enabled: true
  
  # Sound file paths (relative to project root or absolute paths)
  # Use .wav files for best Windows compatibility
  start_sound: assets/sounds/record_start.wav
  stop_sound: assets/sounds/record_stop.wav

# =============================================================================
# SYSTEM TRAY SETTINGS
# =============================================================================
system_tray:
  # Enable/disable system tray icon
  # true = show icon in system tray with status and menu
  # false = run without system tray (console mode only)
  enabled: true
  
  # Tooltip text when hovering over tray icon
  tooltip: Whisper Key
  
  # Show desktop notifications for important events
  # Note: Requires additional setup on some systems
  notifications: false

# =============================================================================
# ADVANCED SETTINGS
# =============================================================================
advanced:
  # Voice Activity Detection (VAD)
  # Automatically detect when speech starts/stops
  vad:
    enabled: false  # Not implemented yet
    threshold: 0.5  # Sensitivity (0.0-1.0)
  
  # Model download settings
  model_cache_dir: null  # null = use default cache directory
  
  # Debugging options
  debug:
    save_audio_files: false  # Save recorded audio for debugging
    audio_output_dir: debug_audio  # Where to save debug audio files
  
